language: rust
matrix:
  fast_finish: true

  include:
      - rust: nightly
        env: FUZZ=1
        sudo: required

      - rust: nightly
        env: COVERAGE=1
        sudo: required

      - rust: stable
        services: docker
        env: TARGET=i686-unknown-linux-gnu
        sudo: required
        addons:
          apt:
            packages:
              - gcc-multilib

      - rust: beta

      - rust: 1.33.0

      - rust: stable
        services: docker
        env: TARGET=mips64-unknown-linux-gnuabi64
        sudo: required

      - rust: stable
        services: docker
        env: TARGET=mips64-unknown-linux-gnuabi64
        sudo: required

      - rust: stable
        env: COVERAGE=1
        sudo: required

cache: cargo
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - ./ci/script.sh
env:
  global:
    secure: Gkb5+OxlL9yrB86RfDHrQF5lFsGP0h4816+P8CvrO1oMBoR6AMlBq0/jfzaNsi4exeij/FD7ELcbsS5dNLW6ayYUgbO4Ql+zkGOu88d2M7ZMZvoYpkYWzMNxTIxkIZxsYmQ3OG0LtpEmuPbkUYYlU49QZqt+xx7+SvA+qfWd9s8=
